=== ssciwr/heiplanet-data/heiplanet_data/setting_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "output_dir": {
            "type": "string",
            "default": "data/processed",
            "description": "Directory where processed data will be saved."
        },
        "adjust_longitude": {
            "type": "boolean",
            "default": true,
            "description": "Whether to adjust longitude values to the range [-180, 180]."
        },
        "adjust_longitude_vname": {
            "type": "string",
            "default": "longitude",
            "description": "Variable name of the longitude values to adjust."
        },
        "adjust_longitude_fname": {
            "type": "string",
            "default": "adjlon",
            "description": "Suffix of file names after adjusting longitude values."
        },
        "convert_kelvin_to_celsius": {
            "type": "boolean",
            "default": true,
            "description": "Whether to convert temperature values from Kelvin to Celsius."
        },
        "convert_kelvin_to_celsius_vname": {
            "type": "string",
            "default": "t2m",
            "description": "Variable name of the temperature values to convert."
        },
        "convert_kelvin_to_celsius_fname": {
            "type": "string",
            "default": "celsius",
            "description": "Suffix of file names after converting temperature values to Celsius."
        },
        "convert_m_to_mm_precipitation": {
            "type": "boolean",
            "default": true,
            "description": "Whether to convert precipitation values from meters to millimeters."
        },
        "convert_m_to_mm_precipitation_vname": {
            "type": "string",
            "default": "tp",
            "description": "Variable name of the precipitation values to convert."
        },
        "convert_m_to_mm_precipitation_fname": {
            "type": "string",
            "default": "mm",
            "description": "Suffix of file names after converting precipitation values to millimeters."
        },
        "resample_grid": {
            "type": "boolean",
            "default": true,
            "description": "Whether to resample the grid to a specified resolution."
        },
        "resample_grid_vname": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "default": ["latitude", "longitude"],
            "description": "Variable names of the latitude and longitude values for resampling."
        },
        "resample_degree": {
            "type": "number",
            "default": 0.5,
            "description": "Value of the target grid resolution."
        },
        "resample_grid_fname": {
            "type": "string",
            "default": "deg_trim",
            "description": "Suffix of file names after resampling the grid."
        },
        "downsample_agg_funcs": {
            "type": "object",
            "patternProperties": {
                "^.*$": {
                    "type": "string"
                }
            },
            "default": null,
            "description": "Aggregation function for each variable during downsampling."
        },
        "upsample_method_map": {
            "type": "object",
            "patternProperties": {
                "^.*$": {
                    "type": "string"
                }
            },
            "default": null,
            "description": "Mapping method for each variable during upsampling."
        },
        "downsample_max_lon_xarray": {
            "type": "number",
            "default": 179.75,
            "description": "Expected maximum longitude value after downsampling with xarray to match population data."
        },
        "downsample_lib": {
            "type": "string",
            "enum": ["xarray", "xesmf", "cdo"],
            "default": "xesmf",
            "description": "Library to use for downsampling. Options are 'xarray', 'xesmf', or 'cdo'."
        },
        "downsample_new_min_lat": {
            "type": "number",
            "default": null,
            "description": "Minimum latitude of the new grid. Used for xesmf and cdo downsampling."
        },
        "downsample_new_max_lat": {
            "type": "number",
            "default": null,
            "description": "Maximum latitude of the new grid. Used for xesmf downsampling."
        },
        "downsample_new_min_lon": {
            "type": "number",
            "default": null,
            "description": "Minimum longitude of the new grid. Used for xesmf and cdo downsampling."
        },
        "downsample_new_max_lon": {
            "type": "number",
            "default": null,
            "description": "Maximum longitude of the new grid. Used for xesmf downsampling."
        },
        "downsample_new_lat_size": {
            "type": "integer",
            "default": null,
            "description": "Number of latitude points in the new grid. Used for cdo downsampling."
        },
        "downsample_new_lon_size": {
            "type": "integer",
            "default": null,
            "description": "Number of longitude points in the new grid. Used for cdo downsampling."
        },
        "downsample_gridtype": {
            "type": "string",
            "enum": ["gaussian", "lonlat", "curvilinear", "unstructured"],
            "default": "lonlat",
            "description": "Type of the grid for downsampling with cdo. Options are 'gaussian', 'lonlat', 'curvilinear', or 'unstructured'."
        },
        "truncate_date": {
            "type": "boolean",
            "default": true,
            "description": "Whether to truncate the time series from a specified date."
        },
        "truncate_date_from": {
            "type": "string",
            "default": "2016-01-01",
            "description": "Date in YYYY-MM-DD to truncate the time series from."
        },
        "truncate_date_to": {
            "type": "string",
            "default": "2017-12-31",
            "description": "Date in YYYY-MM-DD to truncate the time series to."
        },
        "truncate_date_vname": {
            "type": "string",
            "default": "time",
            "description": "Variable name of the time values to truncate."
        },
        "unify_coords": {
            "type": "boolean",
            "default": true,
            "description": "Whether to unify coordinate names in the data file."
        },
        "unify_coords_fname": {
            "type": "string",
            "default": "unicoords",
            "description": "Suffix of file names after unifying coordinate names."
        },
        "uni_coords": {
            "type": "object",
            "patternProperties": {
                "^.*$": {
                    "type": "string"
                }
            },
            "default": {
                "lat": "latitude",
                "lon": "longitude",
                "valid_time": "time"
            },
            "description": "Mapping of variable names to their new names."
        },
        "cal_monthly_tp": {
            "type": "boolean",
            "default": false,
            "description": "Whether to calculate monthly total precipitation based on data downloaded from ERA5-Land monthly data. The real precipitation of the month = downloaded value * number of days in the month."
        },
        "cal_monthly_tp_vname": {
            "type": "string",
            "default": "tp",
            "description": "Variable name of the precipitation values to calculate monthly total precipitation."
        },
        "cal_monthly_tp_tcoord": {
            "type": "string",
            "default": "time",
            "description": "Time coordinate name of the precipitation variable."
        },
        "cal_monthly_tp_fname": {
            "type": "string",
            "default": "montp",
            "description": "Suffix of file names after calculating monthly total precipitation."
        }
    },
    "additionalProperties": false,
    "allOf": [
        {
            "if": {
                "required": ["adjust_longitude"],
                "properties": {
                    "adjust_longitude": { "const": true }
                }
            },
            "then": {
                "required": ["adjust_longitude_vname", "adjust_longitude_fname"]
            }
        },
        {
            "if": {
                "required": ["convert_kelvin_to_celsius"],
                "properties": {
                    "convert_kelvin_to_celsius": { "const": true }
                }
            },
            "then": {
                "required": ["convert_kelvin_to_celsius_vname", "convert_kelvin_to_celsius_fname"]
            }
        },
        {
            "if": {
                "required": ["convert_m_to_mm_precipitation"],
                "properties": {
                    "convert_m_to_mm_precipitation": { "const": true }
                }
            },
            "then": {
                "required": ["convert_m_to_mm_precipitation_vname", "convert_m_to_mm_precipitation_fname"]
            }
        },
        {
            "if": {
                "required": ["resample_grid"],
                "properties": {
                    "resample_grid": { "const": true }
                }
            },
            "then": {
                "required": ["resample_grid_vname", "resample_degree", "resample_grid_fname"]
            }
        },
        {
            "if": {
                "required": ["truncate_date"],
                "properties": {
                    "truncate_date": { "const": true }
                }
            },
            "then": {
                "required": ["truncate_date_from", "truncate_date_to", "truncate_date_vname"]
            }
        },
        {
            "if": {
                "required": ["unify_coords"],
                "properties": {
                    "unify_coords": { "const": true }
                }
            },
            "then": {
                "required": ["unify_coords_fname", "uni_coords"]
            }
        },
        {
            "if": {
                "required": ["cal_monthly_tp"],
                "properties": {
                    "cal_monthly_tp": { "const": true }
                }
            },
            "then": {
                "required": ["cal_monthly_tp_vname", "cal_monthly_tp_tcoord", "cal_monthly_tp_fname"]
            }
        }
    ]
}

=== ssciwr/heiplanet-data/heiplanet_data/era5_settings.json
{
    "output_dir": "processed",
    "adjust_longitude": true,
    "adjust_longitude_vname": "longitude",
    "adjust_longitude_fname": "adjlon",
    "convert_kelvin_to_celsius": true,
    "convert_kelvin_to_celsius_vname": "t2m",
    "convert_kelvin_to_celsius_fname": "celsius",
    "convert_m_to_mm_precipitation": true,
    "convert_m_to_mm_precipitation_vname": "tp",
    "convert_m_to_mm_precipitation_fname": "mm",
    "resample_grid": true,
    "resample_grid_vname": ["latitude", "longitude"],
    "resample_degree": 0.5,
    "resample_grid_fname": "deg_trim",
    "downsample_lib": "xesmf",
    "downsample_new_min_lat": -89.75,
    "downsample_new_max_lat": 89.75,
    "downsample_new_min_lon": -179.75,
    "downsample_new_max_lon": 179.75,
    "unify_coords": true,
    "unify_coords_fname": "unicoords",
    "uni_coords": {
        "valid_time": "time"
    }
}
